### ISSUE TITLE
Why using Java 6?

### ISSUE THREAD

**Issue by tusharjoshi** [Shreerang17hartalkar/Core-Java-Repository#1]
https://github.com/Shreerang17hartalkar/Core-Java-Repository/blob/c5c6c5168a0e9f37a0cea4e1748b7cd35405b379/MavenWorld/pom.xml#L14

Looks like you are still using Java 6, ideally you should be using Java 8 for all your projects now and onwards

**Comment by Shreerang17hartalkar** [comment]
I have started using Java 8 now.I was using Eclipse Kepler,it was showing me the compiler compliance was up to Java 7 only.I tried to download patches as solution for Java 8 but somehow it did not got added.Now I am using Eclipse Oxygen and I am using Java 8 in it.
