### ISSUE TITLE
Follow clean code conventions - one class in a file only

### ISSUE THREAD

**Issue by tusharjoshi** [Shreerang17hartalkar/Core-Java-Repository#3]
https://github.com/Shreerang17hartalkar/Core-Java-Repository/blob/c5c6c5168a0e9f37a0cea4e1748b7cd35405b379/ExceptionPoc/src/com/custexception/CustomizedException.java#L3

Follow clean code conventions. Only one class shall be kept in one file, for other classes make separate class files

**Comment by Shreerang17hartalkar** [comment]
From now on I will create separate classes for each functionality.I read your comment now only.I will follow this from Collections POCs.

**Comment by tusharjoshi** [comment]
Not only that you should also change the code in this repository to correct
it.
You can push the changes by adding, committing and pushing back in the same
repo
